### ISSUE TITLE
16.04 32bit menu loop

### ISSUE THREAD

**Issue by lxle** [stacefauske/bodhibuilder_2.2.x#1]
All builds fine when using bodhibuilder on a 16.04 32bit ubuntu based system as the iso is created successfully, however upon boot of the live cd the menu items to boot the image just force the counter to start over, memtest works fine but trying to boot loops the countdown.

as a side note, the deb is missing the dependency of isolinux as mandatory

**Comment by lxle** [comment]
After more investigation it looks like when using bodhibuilder on a 32bit machine when trying to boot it's apparently trying to use the 64bit kernel and efi instead of recognizing it's a 32 bit machine and using the appropriate kernel to boot. I'm going to slap a bounty on this, not just for this fix but a donation as well to this project.

**Comment by stacefauske** [comment]
Thanks for troubleshooting this for me. I'm on vacation at the moment and it will be kind of hard for me to get right on the problem, but hopefully later in the week or next week I can dig into it.

**Comment by lxle** [comment]
No problem, the LXLE contributions from our community of users will keep this project funded. BodhiBuilder will be available to LXLE users by default with no silly alterations to the name. It's called BodhiBuilder and thats what LXLE users will see when they use it.  Hope you remember the project and issue when you get home from vacation, which I hope is fun, there is also a bounty to collect. :)

**Comment by stacefauske** [comment]
Would you please leave your log file here, or make it available for download? It would help me troubleshoot. Thanks!

**Comment by lxle** [comment]
[bodhibuilder.txt](https://github.com/stacefauske/bodhibuilder_2.2.x/files/347043/bodhibuilder.txt)

**Comment by stacefauske** [comment]
Thanks for the log file lxle.
Would you be willing to uninstall xorriso from your 32-bit OS, re-run the BB script, and then post back the log file here? I don't necessarily think that it will make a difference with the ISO, but might reveal a clue.

**Comment by lxle** [comment]
[bodhibuilder.txt](https://github.com/stacefauske/bodhibuilder_2.2.x/files/348297/bodhibuilder.txt)

**Comment by stacefauske** [comment]
Thanks. I assume you get the same boot loop with this ISO?

**Comment by lxle** [comment]
yup, same thing, its not looking for the 32bit kernel at boot it's trying to boot the 64

**Comment by stacefauske** [comment]
Ok, give it a try now.
I have added some dependencies and removed one for xresprobe. (Don't think we'll be needing that anyway since Ubuntu isn't set on having it in their repos it seems) And instead of making isolinux a dependency, I have set to install it in the script. If I make it a dependency, this script won't work in 14.04 because isolinux is not an available package in 14.04, and the deb won't even install. (I guess I'd just have to make 2 separate packages for each Ubu, which wouldn't be the end of the world.)
But the main thing I did was to not change vmlinuz.efi to vmlinuz in the 'isolinux.cfg.vesamenu'. This seems counter-intuitive, since it isn't a UEFI install, but it has consistently worked for me.

I was just able to successfully do a virtualbox spin of a non-UEFI 32-bit Ubuntu 16.04. BTW, we don't recommend doing EFI spins with bodhibuilder. But we haven't tested it extensively, so it might work.

Let me know how it goes.

EDIT: Also, I don't know if you've been using my source here or not, but you can download the installable deb's at my sourceforge page -- https://sourceforge.net/projects/bodhibuilder/files/

**Comment by stacefauske** [comment]
Please hold off on testing. I have found another bug with vmlinuz in my script and need to t/s a bit more to get it ironed out.
Will post back when I have a fix.
I'll be removing the "beta-03" deb and will replace it with one that is functioning correctly.
Thx

**Comment by stacefauske** [comment]
Fixed the issue with vmlinuz and put the latest deb up on my SF page as 'bodhibuilder_2.2.beta-03.deb'.
Tested good on 32-bit and 64-bit Ubuntu 16.04. The 64-bit boots successfully in virtualbox on both UEFI and BIOS modes.

**Comment by stacefauske** [comment]
@lxle 
If you get a chance to check this out and verify the fix, please report just a little something back here so I can close the ticket. Or else, I guess I'll just mark it closed in a couple of days if I don't hear back. 
(It's always nice to have someone verify a fix.)
Thanks!

**Comment by lxle** [comment]
working on it now, will let you know,  shortly

**Comment by lxle** [comment]
after several attempts, the iso will boot successfully, however it boots to a login screen. During boot it complains of not being able to find the set user.... invalid user....

[bodhibuilder.txt](https://github.com/stacefauske/bodhibuilder_2.2.x/files/358665/bodhibuilder.txt)

**Comment by stacefauske** [comment]
Strange, I'm not having this issue on any of my spins.
Are you finding it only in the 32-bit spins, or 64b as well?

**Comment by lxle** [comment]
both the 64 bit and the 32 bit do the same thing, it starts up at a login screen instead of booting straight to the desktop, an lxde desktop.

**Comment by lxle** [comment]
After another attempt with the 64bit it booted fine, however the 32bit has the same problem, it seems it isn't creating a user as it complains on boot about 'invalid user' then boots to a login screen

**Comment by lxle** [comment]
the error on the 32bit once booting the newly created iso is   'install: invalid user '

**Comment by stacefauske** [comment]
Just curious, how are you testing your iso? Virtualbox? USB? CD?
And if using media, how are you creating it?

Also could you make the corrupted ISO available for me to download? (maybe temporarily available, I could see why you wouldn't want a corrupted ISO available for anyone who happened across this page) I'd like to mount up the ISO and look through some of the files on it to see what might be causing the issue.

**Comment by lxle** [comment]
I'm testing / booting using virtualbox, after a transfer to a usb stick which I've made sure is formatted correctly and not corrupted. I'll do a fresh spin with the 32 and post the iso for you to download to take a look at. I'll also up the bounty on this issue as you've been very helpful.

**Comment by stacefauske** [comment]
I'm going to try a 32b Lubuntu spin to see what turns up.

**Comment by lxle** [comment]
https://sourceforge.net/projects/lxle/files/Betas/old/bodhibuilder.iso/download

**Comment by stacefauske** [comment]
I just created a 32b Lubuntu ISO with no user problems.
- Installed to VB --Made sure the ISO user was the same as the OS user (I believe that is the case with your system, correct? user = qwerty)
- Installed VB-guest stuff
- Installed bodhibuilder dependencies
- Created the ISO
- ISO booted in VB with no issues

I'm currently uploading my ISO so you can check it out and see if it boots on your VB install. (I'll post a link when it's uploaded, probably in the morning) And I'm downloading your ISO to check it out. This one is a head scratcher for me, but I'm confident we can get it sorted. Maybe some package got uninstalled on your system that is still on my Lubuntu install? I'll do a compare on packages and see if something raises any flags.
If we can figure out that it's a package, I'll just make it a dependency so we don't run into this again.
Could you do a compare of installed packages on your 64b vs 32b systems? Maybe something will raise its ugly head.

**Comment by lxle** [comment]
its something in my build, i'm going to start from scratch doing periodic builds to see if i can pin point what went screwy with the initial 32bit build. I'll keep you posted.

**Comment by lxle** [comment]
turned out to be a file/preference that was set and or included in skel, seems to be working as expected, great work and thanks for the help

**Comment by stacefauske** [comment]
No prob. Thanks for finding and helping me work through a bug.
My next beta release (beta-04) will include the option for adding custom repositories in the file /etc/bodhibuilder/apt/custom_repos. So you may want to be on the lookout for that. (Seems a little more logical and easier to me than putting custom repos into the 'firstboot' file) I just have to roll it up into a deb, hopefully by this weekend.
Marking as closed.
