### ISSUE TITLE
Bodhibuilder deleted my ~/Music folder

### ISSUE THREAD

**Issue by pemartins1** [stacefauske/bodhibuilder_2.2.x#12]
Bodhibuilder deleted my ~/Music folder while creating a backup iso. Already searched for its content in the system but it is nowhere to be found.

The iso created is 5.6 GB.

Please let me know an email address or some other way I can send you the bodhibuilder.log file, for privacy concerns I rather not post it publicly. 

My system info:

> System:    Host: pemartins-X55U Kernel: 4.15.0-39-generic x86_64 bits: 64 Desktop: KDE Plasma 5.14.3
>            Distro: KDE Neon BK
> Machine:   Device: laptop System: ASUSTeK product: X55U v: 1.0 serial: N/A
>            Mobo: ASUSTeK model: X55U v: 1.0 serial: N/A
>            UEFI: American Megatrends v: X55U.423 date: 08/06/2013
> Battery    BAT0: charge: 40.0 Wh 97.9% condition: 40.9/47.5 Wh (86%)
> CPU:       Dual core AMD E2-1800 APU with Radeon HD Graphics (-MCP-) cache: 512 KB
>            clock speeds: max: 1700 MHz 1: 1254 MHz 2: 1260 MHz
> Graphics:  Card: Advanced Micro Devices [AMD/ATI] Wrestler [Radeon HD 7340]
>            Display Server: x11 (X.Org 1.19.6 ) driver: radeon Resolution: 1366x768@60.01hz
>            OpenGL: renderer: AMD PALM (DRM 2.50.0 / 4.15.0-39-generic, LLVM 6.0.0)
>            version: 3.3 Mesa 18.0.5
> Audio:     Card-1 Advanced Micro Devices [AMD] FCH Azalia Controller driver: snd_hda_intel
>            Card-2 Advanced Micro Devices [AMD/ATI] Wrestler HDMI Audio driver: snd_hda_intel
>            Sound: Advanced Linux Sound Architecture v: k4.15.0-39-generic
> Network:   Card-1: Ralink RT5390 Wireless 802.11n 1T/1R PCIe driver: rt2800pci
>            IF: wlp1s0 state: up mac: <filter>
>            Card-2: Qualcomm Atheros AR8161 Gigabit Ethernet driver: alx
>            IF: enp2s0 state: down mac: <filter>
> Drives:    HDD Total Size: 500.1GB (12.5% used)
>            ID-1: /dev/sda model: ST500LM012_HN size: 500.1GB
> Partition: ID-1: / size: 78G used: 55G (75%) fs: ext4 dev: /dev/sda5
>            ID-2: swap-1 size: 3.85GB used: 0.00GB (0%) fs: swap dev: /dev/sda6
> RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
> Sensors:   System Temperatures: cpu: 60.0C mobo: N/A gpu: 60.0
>            Fan Speeds (in rpm): cpu: 2800
> Info:      Processes: 179 Uptime: 1:32 Memory: 1937.9/3528.9MB Client: Unknown : systemd inxi: 2.3.56

**Comment by stacefauske** [comment]
Message removed

**Comment by stacefauske** [comment]
Investigating

**Comment by stacefauske** [comment]
In version 2.18.5, removed bodhibuilder-skelcopy -aka- "User, whose current settings will be used as default" (in the gui). It's causing issues with some users. Removing and not fixing this because there are so many possible different configurations of $HOME directories that it is impossible to account for everything that could possibly go wrong. And I don't want it to delete, change, or move something that the user never intended.
