### ISSUE TITLE
2.1.1 needs to be updated on SourceForge

### ISSUE THREAD

**Issue by Shellcat-Zero** [stacefauske/bodhibuilder_2.2.x#3]
Hi,

I can't file an issue in your 2.1.1 repo and I'm not familiar enough with SourceForge to do it there either.  I realize the syslinux-utils dependency issue was fixed in your git repo for 14.04 so I installed it from there, as the deb file on SourceForge will not install due to the issue being present, so I just wanted to remind you to update it there.  Thanks for all your work on Bodhibuilder.  Cheers!

**Comment by stacefauske** [comment]
Thanks, got it.
Hope to have the new one uploaded today (v2.1.2). Will do a little testing first.

**Comment by stacefauske** [comment]
@Shellcat-Zero ,
I have added the "issues" tab to bodhibuilder_2.1.x, and have transferred this issue over there. Please reference the following link for status on this issue.
https://github.com/stacefauske/bodhibuilder/issues/1

Closing & transferring issue.

**Comment by stacefauske** [comment]
bb_2.1.2 uploaded to sourceforge
