### ISSUE TITLE
custom repositories

### ISSUE THREAD

**Issue by lxle** [stacefauske/bodhibuilder_2.2.x#5]
seems that any added repositories are not being added to a newly installed system. PPA's are carried over, but actual added repositories are not.

**Comment by lxle** [comment]
trying the update, seen this was fixed. will report back

**Comment by lxle** [comment]
nope, seems even with the latest version, any custom repositories are ignored once the system is installed. PPA's are carried over but not custom repositories.

**Comment by stacefauske** [comment]
Correct that you are adding your custom repo's to the file "/etc/bodhibuilder/apt/custom_repos" ?

**Comment by lxle** [comment]
ya, i saw it after I posted. Just gave it a shot and it worked just fine..  slick.

**Comment by stacefauske** [comment]
Yeah, we changed it up a little bit, thought it seemed like a good idea. I added some comments to the help that will hopefully make things a little bit clearer. We won't roll out a new version for some help verbiage though, it will just have to hit the next release when there's a fix worth a revision change.
Closing issue.
